# This is a basic workflow to help you get started with Actions

name: PublishToPub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'pubspec.yaml'
          propertyPath: 'version'
          value: 0.0.${{github.run_number}}
          commitChange: false
          updateFile: true
      - name: Write File
        # You may pin to the exact commit or the version.
        # uses: DamianReeves/write-file-action@e19fd875ed54f16fc583a3486e62547ce4a5dde8
        uses: DamianReeves/write-file-action@v1.0
        with:
          # The path to the file to write
          path: CHANGELOG.md
          # The contents of the file
          contents: |
            ## 0.1.${{github.run_number}}
            Changes.
          # The mode of writing to use: `overwrite`, `append`, or `preserve`.
          write-mode: overwrite
#       - name: Set changelog
#         run: >
#           echo "## 0.1.{github.run_number}}" >> CHANGELOG.md
#           echo "changes" >> CHANGELOG.md
      - name: Publish Dart/Flutter package
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.CREDENTIALS }}
          flutter_package: true
          skip_test: true # One day I should write some tests
          dry_run: false
